/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for the markdown formatter */
export interface FormatOptions {
  /** Target line width for wrapping (default: 80) */
  width?: number
  /** How to wrap prose: "always", "never", or "preserve" (default: "preserve") */
  wrap?: string
}
/** Result of a format operation */
export interface FormatResult {
  /** The formatted markdown content */
  content: string
  /** Whether the content was changed */
  changed: boolean
}
/**
 * Format a markdown string with the given options.
 *
 * @param input - The markdown string to format
 * @param options - Optional formatting options
 * @returns The formatted markdown string
 */
export declare function formatMarkdown(input: string, options?: FormatOptions | undefined | null): string
/**
 * Format a markdown string and return both the result and whether it changed.
 *
 * @param input - The markdown string to format
 * @param options - Optional formatting options
 * @returns An object with `content` (formatted string) and `changed` (boolean)
 */
export declare function formatMarkdownWithResult(input: string, options?: FormatOptions | undefined | null): FormatResult
/**
 * Check if a markdown string is already properly formatted.
 *
 * @param input - The markdown string to check
 * @param options - Optional formatting options
 * @returns true if the content is already formatted, false otherwise
 */
export declare function checkMarkdown(input: string, options?: FormatOptions | undefined | null): boolean
